# Theme
remote_theme: pages-themes/cayman

# Site settings
title: AdsTxt Inspector
description: Chrome extension for ads.txt and sellers.json validation
baseurl: '/adstxt-Inspector'
url: 'https://miyaichi.github.io'

# GitHub settings
github:
  repository_url: https://github.com/miyaichi/adstxt-Inspector
  is_project_page: true
  owner_url: https://github.com/miyaichi
  owner_name: miyaichi

# Theme settings
show_downloads: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  parse_block_html: true # Enable parsing of Markdown inside HTML blocks
  syntax_highlighter_opts:
    disable: true # Disable syntax highlighting for mermaid blocks

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Defaults
defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      path: 'en'
    values:
      lang: en
  - scope:
      path: 'ja'
    values:
      lang: ja

# Add mermaid settings
mermaid:
  version: '10.9.0'

# Add custom scripts to head
head_scripts:
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.9.0/mermaid.min.js
